# Generated by Django 5.0.1 on 2024-01-27 22:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tablero', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cedula', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('D', 'Divisas'), ('PM', 'Pago Movil'), ('T', 'Transferencia'), ('B', 'Binance'), ('Z', 'Zinli'), ('PY', 'Paypal'), ('PDV', 'Punto de Venta'), ('TC', 'Tarjeta de Credito'), ('BP', 'Biopago')], default='Divisas', max_length=100)),
                ('moneda', models.CharField(choices=[('D', 'Dolares'), ('BS', 'Bolivares'), ('PCO', 'Pesos CO'), ('US', 'USDT'), ('BT', 'BTC')], default='Dolares', max_length=100)),
            ],
            options={
                'verbose_name': 'Metodo de Pago',
                'verbose_name_plural': 'Metodos de Pagos',
                'db_table': 'MetodoPago',
            },
        ),
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('importe', models.FloatField(max_length=50)),
                ('id_metodoPago', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recep.metodopago', verbose_name='Metodo de Pago')),
            ],
            options={
                'verbose_name': 'Ingreso',
                'verbose_name_plural': 'Ingresos',
                'db_table': 'Ingreso',
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('factura', models.CharField()),
                ('fechaEntrada', models.DateTimeField(auto_now_add=True, verbose_name='CheckIn')),
                ('fechaSalida', models.DateTimeField(blank=True, null=True, verbose_name='CheckOut')),
                ('estadoReserva', models.CharField(choices=[('D', 'Pagada'), ('BS', 'Cancelada'), ('PCO', 'Por Pagar'), ('US', 'Reservada')], default='Pagada', max_length=50)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recep.cliente')),
                ('habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tablero.habitacion')),
                ('importe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recep.ingreso')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
