# Generated by Django 5.0.1 on 2024-01-25 14:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tablero', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('code', models.AutoField(primary_key=True, serialize=False)),
                ('monto', models.PositiveSmallIntegerField(default=30)),
                ('pago', models.CharField(max_length=20)),
                ('fechaEntrada', models.DateTimeField(auto_now_add=True, verbose_name='CheckIn')),
                ('cliente', models.CharField(max_length=30)),
                ('cedula', models.CharField(max_length=10)),
                ('contacto', models.CharField(max_length=20)),
                ('habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tablero.habitacion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
