# Generated by Django 5.0.1 on 2024-01-30 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tablero', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cedula', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fechaEntrada', models.DateTimeField(auto_now_add=True, verbose_name='CheckIn')),
                ('fechaSalida', models.DateTimeField(blank=True, null=True, verbose_name='CheckOut')),
                ('importe', models.FloatField(max_length=10)),
                ('metodoPago', models.CharField(choices=[('Divisas', 'Divisas'), ('Pago Movil', 'Pago Movil'), ('Transferencia', 'Transferencia'), ('Binance', 'Binance'), ('Zinli', 'Zinli'), ('Paypal', 'Paypal'), ('Punto de Venta', 'Punto de Venta'), ('Tarjeta de Credito', 'Tarjeta de Credito'), ('Biopago', 'Biopago')], default='Divisas', max_length=100)),
                ('moneda', models.CharField(choices=[('Dolares', 'Dolares'), ('Bolivares', 'Bolivares'), ('Pesos CO', 'Pesos CO'), ('USDT', 'USDT'), ('BTC', 'BTC')], default='Dolares', max_length=100)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recep.cliente')),
                ('habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tablero.habitacion')),
            ],
        ),
    ]
