# Generated by Django 5.0.1 on 2024-01-27 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recep', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingreso',
            name='id_metodoPago',
        ),
        migrations.AlterField(
            model_name='reserva',
            name='importe',
            field=models.FloatField(max_length=50),
        ),
        migrations.AddField(
            model_name='reserva',
            name='metodoPago',
            field=models.CharField(choices=[('Divisas', 'Divisas'), ('Pago Movil', 'Pago Movil'), ('Transferencia', 'Transferencia'), ('Binance', 'Binance'), ('Zinli', 'Zinli'), ('Paypal', 'Paypal'), ('Punto de Venta', 'Punto de Venta'), ('Tarjeta de Credito', 'Tarjeta de Credito'), ('Biopago', 'Biopago')], default='Divisas', max_length=100),
        ),
        migrations.AddField(
            model_name='reserva',
            name='moneda',
            field=models.CharField(choices=[('Dolares', 'Dolares'), ('Bolivares', 'Bolivares'), ('Pesos CO', 'Pesos CO'), ('USDT', 'USDT'), ('BTC', 'BTC')], default='Dolares', max_length=100),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='estadoReserva',
            field=models.CharField(choices=[('Pagada', 'Pagada'), ('Cancelada', 'Cancelada'), ('Por Pagar', 'Por Pagar'), ('Reservada', 'Reservada')], default='Pagada', max_length=50),
        ),
        migrations.DeleteModel(
            name='MetodoPago',
        ),
        migrations.DeleteModel(
            name='Ingreso',
        ),
    ]
