# Generated by Django 5.0.1 on 2024-01-28 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recep', '0002_remove_ingreso_id_metodopago_alter_reserva_importe_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='estadoReserva',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='factura',
        ),
    ]
