# Generated by Django 5.0.1 on 2024-01-30 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recep', '0002_remove_reserva_importe'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='importe',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='tiempoEstadia',
            field=models.PositiveIntegerField(null=True, verbose_name='Dias de Estadia'),
        ),
    ]
