# Generated by Django 5.0.1 on 2024-01-31 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recep', '0003_reserva_importe_reserva_tiempoestadia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='apellido',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cedula',
            field=models.IntegerField(max_length=9, unique=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='correo',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='metodoPago',
            field=models.CharField(choices=[('Divisas', 'Divisas'), ('Pago Movil', 'Pago Movil'), ('Transferencia', 'Transferencia'), ('Binance', 'Binance'), ('Zinli', 'Zinli'), ('Paypal', 'Paypal'), ('Punto de Venta', 'Punto de Venta'), ('Tarjeta de Credito', 'Tarjeta de Credito'), ('Biopago', 'Biopago')], default='Divisas'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='moneda',
            field=models.CharField(choices=[('Dolares', 'Dolares'), ('Bolivares', 'Bolivares'), ('Pesos CO', 'Pesos CO'), ('USDT', 'USDT'), ('BTC', 'BTC')], default='Dolares'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='tiempoEstadia',
            field=models.IntegerField(max_length=2, null=True, verbose_name='Dias de Estadia'),
        ),
    ]
