# Generated by Django 5.0.1 on 2024-01-28 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recep', '0004_alter_reserva_importe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cedula',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
