# Generated by Django 5.0.1 on 2024-02-01 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recep', '0005_alter_reserva_cliente_alter_reserva_habitacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='apellido',
            field=models.CharField(max_length=15, verbose_name='Escribe el apellido del Cliente'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cedula',
            field=models.CharField(max_length=9, unique=True, verbose_name='Ingresa la Cedula del Cliente'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='correo',
            field=models.EmailField(max_length=50, verbose_name='Inngresa el correo del Cliente'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(max_length=15, verbose_name='Escribe el nombre del Cliente'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(max_length=12, verbose_name='Ingresa el numero telefonico del Cliente'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='tiempoEstadia',
            field=models.IntegerField(null=True, verbose_name='Dias de Estadia del Cliente'),
        ),
    ]
