# Generated by Django 5.0.1 on 2024-01-29 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recep', '0005_alter_cliente_cedula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='importe',
            field=models.FloatField(max_length=10),
        ),
    ]
