# Generated by Django 5.0.1 on 2024-02-01 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recep', '0006_alter_cliente_apellido_alter_cliente_cedula_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='tiempoEstadia',
        ),
    ]
