# Generated by Django 5.0.1 on 2024-01-27 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoHabitacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('D', 'Disponible'), ('O', 'Ocupado'), ('M', 'Mantenimiento'), ('R', 'Reservada')], default='Disponible', max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
                ('precio', models.FloatField(max_length=100)),
            ],
            options={
                'verbose_name': 'Tipo de Habitacion',
                'verbose_name_plural': 'Tipos de Habitaciones',
                'db_table': 'TipoHabitacion',
            },
        ),
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.IntegerField()),
                ('estado', models.CharField(max_length=50)),
                ('id_tipoHabitacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tablero.tipohabitacion', verbose_name='Tipo de Habitacion')),
            ],
            options={
                'verbose_name': 'Habitacion',
                'verbose_name_plural': 'Habitaciones',
                'db_table': 'Habitacion',
            },
        ),
    ]
