# Generated by Django 5.0.1 on 2024-01-30 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablero', '0002_alter_habitacion_estado_alter_habitacion_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitacion',
            name='numero',
            field=models.IntegerField(max_length=3, unique=True),
        ),
    ]
