# Generated by Django 5.0.1 on 2024-01-30 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablero', '0003_alter_habitacion_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitacion',
            name='numero',
            field=models.CharField(max_length=3, unique=True),
        ),
        migrations.AlterField(
            model_name='habitacion',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
