# Generated by Django 5.0.1 on 2024-01-28 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablero', '0004_alter_habitacion_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipohabitacion',
            name='precio',
            field=models.FloatField(max_length=20),
        ),
        migrations.AlterField(
            model_name='tipohabitacion',
            name='tipo',
            field=models.CharField(choices=[('Doble Individual', 'Doble Individual'), ('Triple Individual', 'Triple Individual'), ('Matrimonial + Individual', 'Matrimonial + Individual'), ('Doble Matrimonial', 'Doble Matrimonial'), ('Matrimonial Queen', 'Matrimonial Queen'), ('Matrimonial King', 'Matrimonial King'), ('Matrimonial', 'Matrimonial')], default='Doble Individual', max_length=50),
        ),
    ]
