# Generated by Django 5.0.1 on 2024-01-31 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablero', '0004_alter_habitacion_numero_alter_habitacion_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitacion',
            name='moneda',
            field=models.CharField(choices=[('Dolares', 'Dolares'), ('Bolivares', 'Bolivares'), ('Pesos CO', 'Pesos CO'), ('USDT', 'USDT'), ('BTC', 'BTC')], default='Dolares'),
        ),
        migrations.AlterField(
            model_name='habitacion',
            name='estado',
            field=models.CharField(choices=[('Disponible', 'Disponible'), ('Ocupado', 'Ocupado'), ('Mantenimiento', 'Mantenimiento'), ('Reservada', 'Reservada')]),
        ),
        migrations.AlterField(
            model_name='habitacion',
            name='numero',
            field=models.IntegerField(max_length=3, unique=True),
        ),
        migrations.AlterField(
            model_name='habitacion',
            name='tipo',
            field=models.CharField(choices=[('Doble Individual', 'Doble Individual'), ('Triple Individual', 'Triple Individual'), ('Matrimonial + Individual', 'Matrimonial + Individual'), ('Doble Matrimonial', 'Doble Matrimonial'), ('Matrimonial Queen', 'Matrimonial Queen'), ('Matrimonial King', 'Matrimonial King'), ('Matrimonial', 'Matrimonial')]),
        ),
    ]
