# Generated by Django 5.0.1 on 2024-01-31 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablero', '0005_habitacion_moneda_alter_habitacion_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitacion',
            name='estado',
            field=models.CharField(choices=[('Disponible', 'Disponible'), ('Ocupado', 'Ocupado'), ('Mantenimiento', 'Mantenimiento'), ('Reservada', 'Reservada')], default='Disponible', verbose_name='Selecciona el estado por defecto que tendra la habitacion'),
        ),
        migrations.AlterField(
            model_name='habitacion',
            name='moneda',
            field=models.CharField(choices=[('Dolares', 'Dolares'), ('Bolivares', 'Bolivares'), ('Pesos CO', 'Pesos CO'), ('USDT', 'USDT'), ('BTC', 'BTC')], default='Dolares', verbose_name='Selecciona la moneda utilizada para el precio de la habitacion'),
        ),
        migrations.AlterField(
            model_name='habitacion',
            name='numero',
            field=models.IntegerField(max_length=2, unique=True, verbose_name='Numero de Habitacion: No pueden repetirse los numeros de habitaciones ya creadas.'),
        ),
        migrations.AlterField(
            model_name='habitacion',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Precio de la Habitacion'),
        ),
        migrations.AlterField(
            model_name='habitacion',
            name='tipo',
            field=models.CharField(choices=[('Doble Individual', 'Doble Individual'), ('Triple Individual', 'Triple Individual'), ('Matrimonial + Individual', 'Matrimonial + Individual'), ('Doble Matrimonial', 'Doble Matrimonial'), ('Matrimonial Queen', 'Matrimonial Queen'), ('Matrimonial King', 'Matrimonial King'), ('Matrimonial', 'Matrimonial')], default='Individual', verbose_name='Selecciona el tipo de Habitacion'),
        ),
    ]
