# Generated by Django 5.0.1 on 2024-02-01 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablero', '0006_alter_habitacion_estado_alter_habitacion_moneda_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitacion',
            name='numero',
            field=models.IntegerField(unique=True, verbose_name='Numero de Habitacion: No pueden repetirse los numeros de habitaciones ya creadas.'),
        ),
    ]
