# Generated by Django 5.0.1 on 2024-01-29 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablero', '0006_alter_habitacion_numero_alter_tipohabitacion_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipohabitacion',
            name='tipo',
            field=models.CharField(choices=[('Doble Individual', 'Doble Individual'), ('Triple Individual', 'Triple Individual'), ('Matrimonial + Individual', 'Matrimonial + Individual'), ('Doble Matrimonial', 'Doble Matrimonial'), ('Matrimonial Queen', 'Matrimonial Queen'), ('Matrimonial King', 'Matrimonial King'), ('Matrimonial', 'Matrimonial')], default='Doble Individual', max_length=50),
        ),
    ]
