# Generated by Django 5.0.1 on 2024-01-29 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tablero', '0008_alter_habitacion_numero'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habitacion',
            old_name='id_tipoHabitacion',
            new_name='tipoHabitacion',
        ),
    ]
